task: "llmseceval"
model_name : "qwen3_8b"  #"gpt4o-mini" # "gpt4o" "deepseek-r1_70b" "gemini-2.5-flash-lite" "qwen3_8b"
temperature: 0.0
max_tokens: 1500
max_cwe_limit: 3

with_plan: true
cwe_extract: true
with_rag: true
with_sec_guide: true
with_sec_all_history: true
with_sec_guide_validate: true

make_draft_code: true
with_sec_else_draft: true
with_analyze_draft_surface: true

with_pre_understand: false

already_cwe: false
already_plan: false
already_code: false
already_sec_guide: false
already_rag: false
already_draft_code: false
only_plan: false
only_direct: false
load_preset: false
sec_docs_rag_k: 2

enable_phase2: true
max_refinement_attempts: 2
enable_functionality_check: true
enable_security_check: true
