_base_: base.yaml
model_name: "qwen3_8b"

with_plan: false
cwe_extract: false
with_rag: false
with_sec_guide: false
with_sec_guide_validate: false

make_draft_code: false
with_sec_else_draft: false
with_analyze_draft_surface: false

only_direct: true

enable_phase2: false
max_refinement_attempts: 0
enable_functionality_check: false
enable_security_check: false
